### PR TITLE
fixed outdated registerElement

### PR DESCRIPTION
**Pull request by som-cs**
I used atom a lot and since it's sunset upset i switched to pulsar  but many packages i used to use are outdated so i am going to fix some of them and this one had many updates but for now i only fixed one. "registerElement" changed to "define" so i just changed that for now.

### CODE REVIEW

**Comment by confused-Techie** [comment]
@som-cs As one of the lead Pulsar devs love to see everyone helping out like this! Fingers crossed your PR is seen and we can get it on the Pulsar Package Registry!

**Comment by steelbrain** [comment]
Can someone from the community verify that this solution works without regressions?

**Comment by som-cs** [comment]
> Can someone from the community verify that this solution works without regressions?

I am finally able to test but it has issues. Closing the PR for now. Will open it when fix all the issues. Thank you

**Comment by som-cs** [comment]
@confused-Techie Hope to help you as much as I can... just a side note I am still a noob XD.

Also happy holidays to you both. Enjoy your day

**Pull request closed without merging**
