### PR TITLE
Support atom-ide busy-signal API

### PR DESCRIPTION
**Pull request by lloiser**
see https://github.com/facebookarchive/atom-ide-ui/blob/master/docs/busy-signal.md

**Motivation**
atom-ide-ui has been archived and sooner or later should be replaced by something else.
This package is already installed by a lot of atom users so it's a perfect fit to add the busy signal API here.

**TODO**
- [ ] tests
- [ ] support `onlyForFile` and `onDidClick` options

The actual implementation happened in the second commit. In the first commit I updated all dependencies, I hope this does not cause any troubles when reviewing it.
I have also skipped the other options from the `BusySignalOptions` object because IMO they are not worth the hassle (at least for the moment).

### CODE REVIEW

**Comment by DamnedScholar** [comment]
For context and posterity: this issue was spurred by and is relevant to a conversation happening on [the Atom Discourse](https://discuss.atom.io/t/impact-of-nuclide-extension-being-removed/61242/) about what parts of the former Facebook project can be rescued and put under community control.

**Comment by steelbrain** [comment]
Hi @lloiser

I've sent a request your way for rights on the repository. I don't think I'll be able to maintain this so feel free to work on this PR and merge this or any other change you find fit, from collaborating with you on other projects, I trust your judgement.

Have fun and thanks for this! 🙇

**Comment by lloiser** [comment]
A quick search on github revealed that there aren't many packages that use the options that were previously provided by the busy signal of atom-ide-ui.
I tried to implement them but I think they unnecessarily complicate the code. So I have decided to not implement them yet. If people are actually missing these features they can be added later.

**Comment by lloiser** [comment]
I will merge and publish a new version tomorrow unless anybody wants to review the code or convince me of implementing these options 😁

**Pull request merged**
